### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by L-Scofano** [vita-epfl/DePOSit#1]
I appreciate the effort and the code-sharing very lot.
The training process takes a long time when using an Nvidia RTX 3090 to train the model (both small and large).
Each epoch can take up to 2 hours for the large model when the batch size is set to 16 (because of memory constraints).
Are you having the same problems or using more powerful setups?
Are there any ways, as far as you're aware, to reduce the training period?
Thank you for taking the time to respond.

**Comment by SaeedSaadatnejad** [comment]
Thanks for your interest. 
You're correct that the training process on a single GPU takes a relatively long time due to the diffusion process. 
We are working on improving its speed in the future.
