### ISSUE TITLE
Regarding Inference Time required by the Model

### ISSUE THREAD

**Issue by aviralchharia** [vita-epfl/DePOSit#2]
Hey, though the model training time is high, due to the computational complexity of denoising diffusion models, can the authors comment on the inference time of their approach? Does the model have high time complexity at inference or can it be implemented for real time inference?

**Comment by SaeedSaadatnejad** [comment]
Hi, 
In terms of inference speed, our model is capable of predicting a 1-second sequence in around 0.5 seconds on a Nvidia RTX 3090, demonstrating real-time performance in our current setup. We intend to focus on enhancing its speed in future iterations.
