### ISSUE TITLE
Request checkpoints

### ISSUE THREAD

**Issue by yhd-ai** [vita-epfl/DePOSit#3]
Hey authors,
I am very interested in your work. Could you please share your pre-trained checkpoints? I want to evaluate your model without training. In addition, your paper mentions that post-processing can enhance any posture prediction model. I wonder if it can be used in stochastic models. It seems that only determinative models are enhanced in this paper.

**Comment by SaeedSaadatnejad** [comment]
Hi,
I uploaded the trained model in the release section.
Yes, post-processing can enhance any prediction model. In the paper, we demonstrated its effectiveness with some models. Applying it to other models should be straightforward.

**Comment by yhd-ai** [comment]
> Hi, I uploaded the trained model in the release section. Yes, post-processing can enhance any prediction model. In the paper, we demonstrated its effectiveness with some models. Applying it to other models should be straightforward.

I‘ve found it! Thank you~

**Comment by yhd-ai** [comment]
And I wrote codes to make the keys aligned. 
BTW, in File "main_tcd_h36m.py",
  `output = model_s.module.evaluate(s, nsample)` seems to be `output = model_s.evaluate(s, nsample)`
cuz 'ModelMain' object has no attribute 'module'

**Comment by SaeedSaadatnejad** [comment]
Thank you for bringing up this issue. The problem was related to training on multi-GPUs and loading on a single-GPU. Have fixed it and made updates to the code and the released model.

**Comment by yhd-ai** [comment]
Learned a lot
