### ISSUE TITLE
The value of cosine noise scheduler

### ISSUE THREAD

**Issue by ShaokangHi** [vita-epfl/DePOSit#4]
Thank you for your grest work!
I saw that you used the cosine noise scheduler in the paper, could you tell me what its values are?

**Comment by SaeedSaadatnejad** [comment]
Thank you for your interest.
This is for noise scheduling of the diffusion process. You can find the corresponding values of betta in the init of the ModelMain class in model.py

**Comment by ShaokangHi** [comment]
Thank you for your reply!
From 'beta_start': 0.0001 to 'beta_end': 0.5, right?

**Comment by SaeedSaadatnejad** [comment]
Sorry i lost your reply. I believe you've already discovered it.
In cosine scheduler, the beta values range from 0.00174751 to 0.5. For additional details, please refer to the "model.py" file.
