### ISSUE TITLE
Dataset link broken

### ISSUE THREAD

**Issue by mmahdavian** [vita-epfl/DePOSit#5]
Hello

Thank you for providing your codes. But the dataset link seems broken. Is it possible for you to provide the dataset link?

Thank You

**Comment by SaeedSaadatnejad** [comment]
Hello,

You can download the human3.6m data from [here](https://drive.google.com/file/d/1iFXl51LbprPhCRUiQzBshAXXsrOtfuOh/view?usp=sharing).
