### ISSUE TITLE
Regarding Usability as 3D Human Pose Keypoint Repair Pipeline

### ISSUE THREAD

**Issue by aviralchharia** [vita-epfl/DePOSit#6]
Hi authors,
Great work! The study mentions that post-processing can be used to enhance the human pose of any prediction model. Can the authors comment if it can be used for repairing key points. For example, if we have only 14 predicted key points in COCO format (from any model like MediaPipe/ YOLOv8), and 3 missing key points. Can the approach be used to predict the remaining key points? Thanks!

**Comment by satijapratik** [comment]
I have the same question^. Can this be addressed?

**Comment by SaeedSaadatnejad** [comment]
Hi, yes it can be used for repairing too.
You just need to set the appropriate observation length and apply TCD on your sequences.
