### ISSUE TITLE
Separation of Pre-Procession Diffusion block from the model

### ISSUE THREAD

**Issue by satijapratik** [vita-epfl/DePOSit#7]
Hey,

The approach mentioned in this paper seems very intriguing and useful. However, I wanted to test out the usage of just the pre-processing phase where the key points are repaired. Are there any particular steps that I can be pointed towards so that I am able to just observe the broken and repaired key points after observation is passed through the Pre-Process Diffusion block?

**Comment by SaeedSaadatnejad** [comment]
Hi,
Thank you! For repairing, you need to set the observation and prediction length so that the model only reconstructs and then train TCD accordingly. Let me know if you encounter any issues.

**Comment by satijapratik** [comment]
Hi Saeed, 

I am entering the following command to run the model in reconstruction model only using the trained model weights that you were given to us by you all. 

`python main_tcd_h36m.py --mode test --data all --joints 22 --input_n 25 --output_n 0 --data_dir data_dir --model_s model_s --model_l model_l --output_dir model_repair --miss_type random`

However, I am running into an error where the Renormalized Pose list is empty:

`Reading subject 5, action walking, subaction 1
Reading subject 5, action walking, subaction 2
>>> Test dataset length: 256
  0%|                                                                                                                                          | 0/8 [00:00<?, ?it/s]Renormalized Pose:  [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
  0%|                                                                                                                                          | 0/8 [00:54<?, ?it/s]
Traceback (most recent call last):
  File "main_tcd_h36m.py", line 561, in <module>
    pose, target, mask, ret = eval(
  File "main_tcd_h36m.py", line 320, in evaluate_32
    renorm_pose = torch.from_numpy(np.array(renorm_pose))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.`

Have you dealt with this issue before?

**Comment by SaeedSaadatnejad** [comment]
Hi 
The provided model was not trained with `--output_n 0`
If you want to use a model in test time with ` --input_n 25 --output_n 0` setting, you need to train one with that setting first.
